config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"

  resources :movies, only: [:index, :show] do
    resources :purchases, only: [:create]
  end

  resources :seasons, only: [:index, :show] do
    resources :purchases, only: [:create]
  end

  resources :contents, only: [:index]

  resources :purchase_options, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/episode.rb
class Episode < ApplicationRecord
  belongs_to :season
end

app/models/library_entry.rb
class LibraryEntry < ApplicationRecord
  belongs_to :user, dependent: :destroy
  belongs_to :content, polymorphic: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :purchase_options, as: :content
  has_many :libray_entries, as: :content
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :user, dependent: :destroy
  belongs_to :purchase_option
end

app/models/purchase_option.rb
class PurchaseOption < ApplicationRecord
  belongs_to :content, polymorphic: true
  has_many :purchases

  HD = "HD"
  SD = "SD"
end

app/models/season.rb
class Season < ApplicationRecord
  has_many :episodes, dependent: :destroy
  has_many :purchase_options, as: :content
  has_many :libray_entries, as: :content
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :purchases
  has_many :libray_entries
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  def index
    @movies = Movie.all
    @seasons = Season.all

    # Create custom hashes for movies and seasons to include the type for sorting later
    @movies_with_type = @movies.map { |movie| { content: movie, type: 'Movie' } }
    @seasons_with_type = @seasons.map { |season| { content: season, type: 'Season' } }

    # Combine both arrays and sort based on the 'created_at' attribute
    @contents = (@movies_with_type + @seasons_with_type).sort_by { |c| c[:content].created_at }

    # Check the sort parameter and adjust the order accordingly
    if params[:sort] == "newest"
      @contents = @contents.reverse
    elsif params[:sort] == "oldest"
      @contents = @contents
    end
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all

    # Check the sort parameter and adjust the order accordingly
    if params[:sort] == "newest"
      @movies = @movies.order(created_at: :desc)
    elsif params[:sort] == "oldest"
      @movies = @movies.order(created_at: :asc)
    end
  end

  def show
    @movie = Movie.find_by(id: params[:id])
    @purchase_options = PurchaseOption.new(content: @movie, price: 2.99)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/purchase_options_controller.rb
class PurchaseOptionsController < ApplicationController
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  def create
    if params[:movie_id].present?
      purchase_movie
    elsif params[:season_id].present?
      purchase_season
    else
      redirect_to contents_path, alert: 'Invalid purchase request.'
    end
  end

  private

  def purchase_movie
    @movie = Movie.find(params[:movie_id])
    purchase_content(@movie)
  end

  def purchase_season
    @season = Season.find(params[:season_id])
    purchase_content(@season)
  end

  def purchase_content(content)
    @purchase_option = PurchaseOption.new(price: 2.99, content: content, video_quality: params[:purchase_option_id])
    if @purchase_option.save
      @purchase = Purchase.new(user: current_user, purchase_option: @purchase_option)
      if @purchase.save
        redirect_to contents_path, notice: 'Purchase was successfully created.'
      else
        render :new, status: :unprocessable_entity
      end
    else
      render :new, status: :unprocessable_entity
    end
  end
end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
  def index
    @seasons = Season.all

    # Check the sort parameter and adjust the order accordingly
    if params[:sort] == "newest"
      @seasons = @seasons.order(created_at: :desc)
    elsif params[:sort] == "oldest"
      @seasons = @seasons.order(created_at: :asc)
    end
  end

  def show
    @season = Season.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contents/index.html.erb
<h1>Content</h1>
<p>
  Sort by:
  <%= link_to "Newest", contents_path(sort: "newest") %>
  <%= link_to "Oldest", contents_path(sort: "oldest") %>
</p>
<div class="row">
  <% @contents.each_with_index do |content, index| %>
    <div class="col-lg-3 col-md-6">
      <div class="content">
        <% if content[:content].is_a?(Movie) %>
          <%= link_to movie_path(content[:content]) do %>
            <h2><%= index + 1 %>. <%= content[:content].title %></h2>
          <% end %>
        <% elsif content[:content].is_a?(Season) %>
          <%= link_to season_path(content[:content]) do %>
            <h2><%= index + 1 %>. <%= content[:content].title %></h2>
            <h3>Episodes</h3>
            <% content[:content].episodes.each do |episode| %>
              <p><%= episode.episode_number %>. <%= episode.title %></p>
            <% end %>
          <% end %>
        <% end %>
        <p><%= content[:content].plot %></p>
        <p>Creation: <%= content[:content].created_at.strftime("%d/%m/%Y %H:%M:%S") %></p>
        <p>Content Type: <%= content[:content].is_a?(Movie) ? "Movie" : "Season" %></p>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StreamingApplicationTest</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="container">
      <%= render "shared/navbar" %>
      <%= render "shared/flashes" %>

      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

      <%= yield %>
    </div>
  </body>
</html>

app/views/movies/index.html.erb
<h1>Movies</h1>

<p>
  Sort by:
  <%= link_to "Newest", movies_path(sort: "newest") %>
  <%= link_to "Oldest", movies_path(sort: "oldest") %>
</p>

<div class="row">
  <% @movies.each_with_index do |movie, index| %>
    <div class="col-lg-3 col-md-6">
      <%= link_to movie_path(movie) do %>
        <div class="content">
          <h2><%= index + 1 %>. <%= movie.title %></h2>
          <p><%= movie.plot %></p>
          <p>Creation: <%= movie.created_at.strftime("%d/%m/%Y %H:%M:%S") %></p>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/movies/show.html.erb
<h1><%= @movie.title %></h1>

<h2><%= @movie.plot %></h2>

<p>Creation: <%= @movie.created_at.strftime("%d/%m/%Y %H:%M:%S") %></p>

<%= render "purchase_options/dropdown_movies" %>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/purchase_options/_dropdown_movies.html.erb
<%= form_with(model: @purchase, url: movie_purchases_path(@movie)) do |form| %>
  <% options = [[PurchaseOption::HD, "HD"], [PurchaseOption::SD, "SD"]] %>
  <%= form.select :purchase_option_id, options_for_select(options) %>
  <%= form.submit "Buy", class: "btn btn-primary" %>
<% end %>

app/views/purchase_options/_dropdown_seasons.html.erb
<%= form_with(model: @purchase, url: season_purchases_path(@season)) do |form| %>
  <% options = [[PurchaseOption::HD, "HD"], [PurchaseOption::SD, "SD"]] %>
  <%= form.select :purchase_option_id, options_for_select(options) %>
  <%= form.submit "Buy", class: "btn btn-primary" %>
<% end %>

app/views/seasons/index.html.erb
<h1>Seasons</h1>
<p>
  Sort by:
  <%= link_to "Newest", seasons_path(sort: "newest") %>
  <%= link_to "Oldest", seasons_path(sort: "oldest") %>
</p>
<div class="row">
  <% @seasons.each_with_index do |season, index| %>
    <div class="col-lg-3 col-md-6">
      <div class="content">
        <%= link_to season_path(season) do %>
          <h2><%= index + 1 %>. <%= season.title %></h2>
          <p><%= season.plot %></p>
          <p>Creation: <%= season.created_at.strftime("%d/%m/%Y %H:%M:%S") %></p>
        <% end %>
        <h3>Episodes</h3>
        <% season.episodes.each do |episode| %>
          <p><%= episode.episode_number %>. <%= episode.title %></p>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/seasons/show.html.erb
<h1><%= @season.title %></h1>

<h2><%= @season.plot %></h2>

<p>Creation: <%= @season.created_at.strftime("%d/%m/%Y %H:%M:%S") %></p>

<h3>Episodes</h3>

<% @season.episodes.each do |episode| %>
  <p><%= episode.episode_number %>. <%= episode.title %></p>
<% end %>

<%= render "purchase_options/dropdown_seasons" %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <h1>Streaming App</h1>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>